'''
Author: liulx
Date: 2023-11-19 22:36:28
LastEditors: liulx, liulx18@qq.com
LastEditTime: 2023-11-19 23:57:54
FilePath: \\nuclear-phsics-and-detection\\source\\conf.py
Description: 
Copyright (c) 2023 by liulx, All Rights Reserved. 
'''
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = '核辐射物理及探测'
copyright = '2023,liulx'
copyright = '2023, liulx'
author = 'liulx'
release = '0.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'recommonmark',
    'sphinx_markdown_tables'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
#
html_search_language = 'zh'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# 简洁，字体看着累
# html_theme = 'sphinxdoc'
# html_theme = 'bizstyle'
# html_theme = 'sphinxdoc'
# 简洁，字体舒服，没有侧边栏
# html_theme = 'haiku'

# read the docs theme.
# html_theme = 'sphinx_rtd_theme'
# html_theme_options = {
#     # 'analytics_id': 'G-XXXXXXXXXX',  #  Provided by Google in your dashboard
#     'analytics_anonymize_ip': True,
#     'logo_only': False,
#     'display_version': True,
#     'prev_next_buttons_location': 'bottom',
#     'style_external_links': False,
#     'vcs_pageview_mode': 'edit',
#     # 'style_nav_header_background': 'white',
#     # Toc options
#     'collapse_navigation': False,
#     'sticky_navigation': True,
#     'navigation_depth': 2,
#     'includehidden': True,
#     'titles_only': False
# }

# 第三方theme（https://github.com/pradyunsg/furo）
html_theme = "furo"
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "SteelBlue",
        "color-brand-content": "SteelBlue",
        "color-admonition-background": "orange",
        "hide-toc": "True",
        "tocdepth": "2"
    },
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_title = "核辐射物理及探测"
html_logo = "_static/atom.png"
